#include "domain.hpp"
null_j* get_null_j(){return new null_j;}
ref* get_ref(){return new ref;}
motor_j* get_motor_j(){return new motor_j;}
mouse_j* get_mouse_j(){return new mouse_j;}
weld_j* get_weld_j(){return new weld_j;}
CollObj* get_CollObj(){return new CollObj;}
display* get_display(){return new display;}
rad* get_rad(){return new rad;}
tfm* get_tfm(){return new tfm;}
Process* get_Process(){return new Process;}
BlendObj* get_BlendObj(){return new BlendObj;}
prismatic_j* get_prismatic_j(){return new prismatic_j;}
_joint* get__joint(){return new _joint;}
game* get_game(){return new game;}
distance_j* get_distance_j(){return new distance_j;}
wheel_j* get_wheel_j(){return new wheel_j;}
Object* get_Object(){return new Object;}
DrawObj* get_DrawObj(){return new DrawObj;}
pos* get_pos(){return new pos;}
revolute_j* get_revolute_j(){return new revolute_j;}
