#pragma once
#include "include.hpp"
null_j* get_null_j();
ref* get_ref();
motor_j* get_motor_j();
mouse_j* get_mouse_j();
weld_j* get_weld_j();
CollObj* get_CollObj();
display* get_display();
rad* get_rad();
tfm* get_tfm();
Process* get_Process();
BlendObj* get_BlendObj();
prismatic_j* get_prismatic_j();
_joint* get__joint();
game* get_game();
distance_j* get_distance_j();
wheel_j* get_wheel_j();
Object* get_Object();
DrawObj* get_DrawObj();
pos* get_pos();
revolute_j* get_revolute_j();
